---
galaxy_info:
  author: FABRIC Team
  description: Install NVIDIA drivers and CUDA toolkit on Rocky 9 / RHEL 9, Ubuntu 22.04, Ubuntu 24.04
  company: FABRIC

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - 9
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - nvidia
    - cuda
    - gpu
    - drivers
    - fabric

dependencies: []
